### numpy

In [1]:
import numpy as np

In [8]:
# get a numpy array of size 30 with equidistant points between 1, 300. 
# Change to 2D ndarray with shape 5, 6
np.linspace( 1, 300, 30 ).reshape((5, 6))

array([[  1.        ,  11.31034483,  21.62068966,  31.93103448,
         42.24137931,  52.55172414],
       [ 62.86206897,  73.17241379,  83.48275862,  93.79310345,
        104.10344828, 114.4137931 ],
       [124.72413793, 135.03448276, 145.34482759, 155.65517241,
        165.96551724, 176.27586207],
       [186.5862069 , 196.89655172, 207.20689655, 217.51724138,
        227.82758621, 238.13793103],
       [248.44827586, 258.75862069, 269.06896552, 279.37931034,
        289.68965517, 300.        ]])

In [12]:
# get the numpy array of 3, 4 using 1 digit random numbers
a1 = np.random.randint( 0, 10, 12 )
a2 = a1.reshape((3, 4))

In [25]:
a3 = np.random.randint( 0, 10, 20 ).reshape((4, 5))
a4 = np.random.randint( 0, 10, 9 ).reshape((3, 3))

In [13]:
a1

array([5, 7, 7, 7, 1, 3, 9, 4, 8, 3, 5, 0])

In [14]:
a2

array([[5, 7, 7, 7],
       [1, 3, 9, 4],
       [8, 3, 5, 0]])

In [15]:
sum(a1)

59

In [16]:
sum(a2)

array([14, 13, 21, 11])

In [20]:
a2.sum( axis = 1 )

array([26, 17, 16])

In [18]:
np.sum(a2)

59

In [23]:
a2

array([[5, 7, 7, 7],
       [1, 3, 9, 4],
       [8, 3, 5, 0]])

In [26]:
a3

array([[4, 4, 8, 1, 0],
       [0, 2, 9, 3, 4],
       [2, 1, 8, 3, 2],
       [2, 0, 2, 7, 6]])

In [27]:
a4

array([[1, 1, 4],
       [1, 5, 4],
       [0, 3, 8]])

In [29]:
np.hstack((a2, a4))

array([[5, 7, 7, 7, 1, 1, 4],
       [1, 3, 9, 4, 1, 5, 4],
       [8, 3, 5, 0, 0, 3, 8]])

In [31]:
np.vstack( (a2, a3.T) )

array([[5, 7, 7, 7],
       [1, 3, 9, 4],
       [8, 3, 5, 0],
       [4, 0, 2, 2],
       [4, 2, 1, 0],
       [8, 9, 8, 2],
       [1, 3, 3, 7],
       [0, 4, 2, 6]])

## Pandas - Panel Data Analysis

In [32]:
import pandas as pd

### Series 

In [37]:
l1 = list(range(1, 51, 10))

In [38]:
l1

[1, 11, 21, 31, 41]

In [42]:
pd.Series( l1, dtype = np.int16, name = 'Col1' )

0     1
1    11
2    21
3    31
4    41
Name: Col1, dtype: int16

In [44]:
s1 = pd.Series([10, 20, 30, 40, 50])

In [45]:
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [50]:
s2 = pd.Series( [10, 20, 30, 40, 50], index = range(1, 6) )

In [51]:
s2

1    10
2    20
3    30
4    40
5    50
dtype: int64

In [53]:
s3 = pd.Series( [10, 20, 30, 40, 50], index = ['a', 'b', 'c', 'd', 'e'] )

In [54]:
s3

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [55]:
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [56]:
s1[1]

20

In [57]:
s1[1:3]

1    20
2    30
dtype: int64

In [58]:
s1[-1]    # instead use .iloc[]

KeyError: -1

In [59]:
s2

1    10
2    20
3    30
4    40
5    50
dtype: int64

In [60]:
s2[2]

20

In [61]:
s2[2:4]

3    30
4    40
dtype: int64

In [62]:
s3

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [63]:
s3['b']

20

In [64]:
s3[1]

20

In [65]:
s3[1:3]

b    20
c    30
dtype: int64

In [66]:
s3['b':'c']

b    20
c    30
dtype: int64

In [67]:
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [68]:
s1[1]

20

In [69]:
s1.iloc[1]

20

In [70]:
s1.loc[1]

20

In [71]:
s1[1:3]

1    20
2    30
dtype: int64

In [72]:
s1.iloc[1:3]

1    20
2    30
dtype: int64

In [73]:
s1.loc[1:3]

1    20
2    30
3    40
dtype: int64

In [74]:
s2

1    10
2    20
3    30
4    40
5    50
dtype: int64

In [75]:
s2.iloc[1]

20

In [76]:
s2.loc[2]

20

In [77]:
s2.iloc[1:3]

2    20
3    30
dtype: int64

In [78]:
s2.loc[2:3]

2    20
3    30
dtype: int64

In [79]:
s2.iloc[-1]

50

In [80]:
s2.iloc[4]

50

In [81]:
s3

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [82]:
s3.loc['d']

40

In [83]:
s3.iloc[3]

40

In [84]:
s3.loc['b':'c']

b    20
c    30
dtype: int64

In [85]:
s3.iloc[1:3]

b    20
c    30
dtype: int64

In [86]:
s3.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [90]:
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [91]:
s1[2] = -1

In [92]:
s1

0    10
1    20
2    -1
3    40
4    50
dtype: int64

In [93]:
s1

0    10
1    20
2    -1
3    40
4    50
dtype: int64

In [95]:
s1[2:4] = 0

In [96]:
s1

0    10
1    20
2     0
3     0
4    50
dtype: int64

In [97]:
s1[2:4] = [-1, -2]

In [98]:
s1

0    10
1    20
2    -1
3    -2
4    50
dtype: int64

In [99]:
s1 

0    10
1    20
2    -1
3    -2
4    50
dtype: int64

In [100]:
s1 / 10

0    1.0
1    2.0
2   -0.1
3   -0.2
4    5.0
dtype: float64

In [103]:
s1

0    10
1    20
2    -1
3    -2
4    50
dtype: int64

In [104]:
s2

1    10
2    20
3    30
4    40
5    50
dtype: int64

In [105]:
s1 + s2

0     NaN
1    30.0
2    19.0
3    28.0
4    90.0
5     NaN
dtype: float64

In [107]:
# Get the series with 20, 2 digit random numbers
s4 = pd.Series( np.random.randint(10, 100, 20) )

In [108]:
s4

0     82
1     94
2     12
3     98
4     69
5     43
6     34
7     68
8     28
9     38
10    28
11    56
12    93
13    57
14    84
15    49
16    49
17    82
18    53
19    46
dtype: int32

In [112]:
# get the data from s4 GE 60
s4[ s4 >= 60 ]

0     82
1     94
3     98
4     69
7     68
12    93
14    84
17    82
dtype: int32

In [113]:
s4.loc[ s4 >= 60 ]

0     82
1     94
3     98
4     69
7     68
12    93
14    84
17    82
dtype: int32

In [114]:
s4.iloc[ s4 >= 50 ]

NotImplementedError: iLocation based boolean indexing on an integer type is not available

In [110]:
# get the data from s4 LE 70
s4[ s4 <= 70 ]

2     12
4     69
5     43
6     34
7     68
8     28
9     38
10    28
11    56
13    57
15    49
16    49
18    53
19    46
dtype: int32

In [129]:
# get the data between 60 and 70
s5 = s4[ (s4 >= 60) & (s4 <= 70) ]

In [127]:
s5

4    69
7    68
dtype: int32

In [122]:
s5.index = [5, 6]

In [123]:
s5

5    69
6    68
dtype: int32

### DataFrame

In [130]:
print(dir(pd))

['BooleanDtype', 'Categorical', 'CategoricalDtype', 'CategoricalIndex', 'DataFrame', 'DateOffset', 'DatetimeIndex', 'DatetimeTZDtype', 'ExcelFile', 'ExcelWriter', 'Flags', 'Float32Dtype', 'Float64Dtype', 'Float64Index', 'Grouper', 'HDFStore', 'Index', 'IndexSlice', 'Int16Dtype', 'Int32Dtype', 'Int64Dtype', 'Int64Index', 'Int8Dtype', 'Interval', 'IntervalDtype', 'IntervalIndex', 'MultiIndex', 'NA', 'NaT', 'NamedAgg', 'Period', 'PeriodDtype', 'PeriodIndex', 'RangeIndex', 'Series', 'SparseDtype', 'StringDtype', 'Timedelta', 'TimedeltaIndex', 'Timestamp', 'UInt16Dtype', 'UInt32Dtype', 'UInt64Dtype', 'UInt64Index', 'UInt8Dtype', '__builtins__', '__cached__', '__doc__', '__docformat__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_config', '_hashtable', '_is_numpy_dev', '_lib', '_libs', '_np_version_under1p17', '_np_version_under1p18', '_testing', '_tslib', '_typing', '_version', 'api', 'array', 'arrays', 'bda

In [133]:
stores = pd.read_csv('D:/SampleData/stores_new.csv')
# always use the forward slash to give the file/dir paths

# D:\SampleData\stores_new.csv
# Avoid using the back slash, bcoz in some Windows versions you have to make use of two backward slash

In [134]:
type(stores)

pandas.core.frame.DataFrame

In [135]:
stores.ndim

2

In [136]:
stores.shape

(32, 16)

In [138]:
stores.dtypes

StoreCode           object
StoreName           object
StoreType           object
Location            object
OperatingCost      float64
Staff_Cnt            int64
TotalSales         float64
Total_Customers      int64
AcqCostPercust     float64
BasketSize         float64
ProfitPercust      float64
Dummy              float64
OwnStore             int64
OnlinePresence       int64
Tenure               int64
StoreSegment         int64
dtype: object

In [140]:
print(dir(stores))

['AcqCostPercust', 'BasketSize', 'Dummy', 'Location', 'OnlinePresence', 'OperatingCost', 'OwnStore', 'ProfitPercust', 'Staff_Cnt', 'StoreCode', 'StoreName', 'StoreSegment', 'StoreType', 'T', 'Tenure', 'TotalSales', 'Total_Customers', '_AXIS_LEN', '_AXIS_ORDERS', '_AXIS_REVERSED', '_AXIS_TO_AXIS_NUMBER', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module