In [1]:
l1 = [10, 20, 30, 40]

In [2]:
l1[1:3] = [1, 2]

In [3]:
l1

[10, 1, 2, 40]

### numpy

In [3]:
import numpy as np

In [5]:
import numpy as np

In [6]:
l1 = [1, 2, 3, 4, 5]

In [7]:
type(l1)

list

In [8]:
np.array(l1)

array([1, 2, 3, 4, 5])

In [9]:
np.array( [[l1, l1], [l1, l1]] )

array([[[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]],

       [[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]]])

In [10]:
np.array([l1,l1])

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [11]:
np.zeros( 5 )

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros( (3, 5) )

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.zeros( (2, 3, 5) )

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [14]:
np.zeros( (2, 3, 5) )

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [15]:
np.ones((5, 7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [16]:
np.full( (5, 3), 'Python' )

array([['Python', 'Python', 'Python'],
       ['Python', 'Python', 'Python'],
       ['Python', 'Python', 'Python'],
       ['Python', 'Python', 'Python'],
       ['Python', 'Python', 'Python']], dtype='<U6')

In [17]:
np.full((3,4),'check')


array([['check', 'check', 'check', 'check'],
       ['check', 'check', 'check', 'check'],
       ['check', 'check', 'check', 'check']], dtype='<U5')

In [18]:
np.full((2,4),'practice')

array([['practice', 'practice', 'practice', 'practice'],
       ['practice', 'practice', 'practice', 'practice']], dtype='<U8')

In [19]:
np.full((3,2),'check')

array([['check', 'check'],
       ['check', 'check'],
       ['check', 'check']], dtype='<U5')

In [20]:
np.array( range(1, 11, 1) )

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
np.array(range(5,51,5))

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [22]:
np.arange(5,51,2) # in arange we have to give (start, end , increment)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

In [23]:
np.arange(0, 1.01, 0.01)

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  ])

In [24]:
np.linspace( 1, 10, 20 )

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [25]:
np.linspace(5,50,25) # in linspace we can give no elements we want to have in array.

array([ 5.   ,  6.875,  8.75 , 10.625, 12.5  , 14.375, 16.25 , 18.125,
       20.   , 21.875, 23.75 , 25.625, 27.5  , 29.375, 31.25 , 33.125,
       35.   , 36.875, 38.75 , 40.625, 42.5  , 44.375, 46.25 , 48.125,
       50.   ])

In [26]:
len(np.linspace(2,60,30))

30

In [27]:
type(np.linspace(2,60,30))

numpy.ndarray

In [28]:
np.random.random(15) # np.random.random only take one argument which define the no of elements in array.
# elements of array lies between 0 and one only.

array([0.02100492, 0.31825326, 0.44814093, 0.5253199 , 0.43013518,
       0.48298595, 0.72112035, 0.05937447, 0.08297247, 0.55932888,
       0.97204321, 0.74213949, 0.29523829, 0.54972979, 0.22729275])

In [29]:
np.random.random( 100 )

array([0.46691001, 0.71843087, 0.6512736 , 0.29442993, 0.89274026,
       0.09056019, 0.98310786, 0.83714154, 0.48250466, 0.04869478,
       0.12863305, 0.57660298, 0.76733313, 0.46488245, 0.43411121,
       0.97934848, 0.68444749, 0.04777719, 0.28211735, 0.78199321,
       0.3726037 , 0.51281688, 0.06025372, 0.80837019, 0.93041524,
       0.36629932, 0.99166439, 0.85311396, 0.35847156, 0.51951312,
       0.94873977, 0.60977039, 0.40394927, 0.89827471, 0.26259635,
       0.10649397, 0.01981443, 0.2028538 , 0.92588769, 0.62056775,
       0.38074435, 0.08154244, 0.35476963, 0.67769574, 0.90626139,
       0.25150371, 0.33599232, 0.21070749, 0.62787287, 0.96369675,
       0.42382983, 0.30890708, 0.0648755 , 0.62672018, 0.77811766,
       0.41246754, 0.53846597, 0.00793794, 0.0964627 , 0.67184661,
       0.7163213 , 0.54046275, 0.17156514, 0.75200406, 0.43487592,
       0.9572843 , 0.80829334, 0.00951968, 0.23508243, 0.40167339,
       0.74723929, 0.81785597, 0.59748641, 0.05899284, 0.54363

In [30]:
# get 15 two digit random numbers  # np.random.randint take three arguments ( floor value, celling value, no of elements in array)
np.random.randint( 10, 100, 15 )

array([33, 15, 36, 54, 15, 58, 18, 56, 51, 65, 21, 36, 35, 64, 33])

In [31]:
#grt 20 two digit random numbers
np.random.randint(10,99,20)

array([28, 91, 97, 19, 50, 32, 80, 88, 93, 13, 83, 51, 55, 11, 54, 70, 64,
       28, 78, 11])

In [4]:
# get 20 three digit random numbers in the shape 4, 5
a1 = np.random.randint(100, 1000, 20)

In [33]:
a1

array([262, 974, 149, 959, 997, 260, 648, 436, 716, 385, 873, 634, 682,
       483, 854, 453, 653, 154, 876, 838])

In [34]:
# get 10 foure digit random numbers.
G=np.random.randint(1000,10000,10)

In [35]:
G

array([1703, 9369, 1894, 5512, 2325, 5908, 6886, 5218, 1407, 4095])

In [36]:
G.ndim   # .ndim gives the dimension of given array.

1

In [37]:
type(G)

numpy.ndarray

In [38]:
G.shape

(10,)

In [39]:
# .ndim gives the dimension of the given array

In [40]:
type(a1)

numpy.ndarray

In [41]:
a1.ndim

1

In [42]:
a1.shape

(20,)

In [43]:
a1

array([262, 974, 149, 959, 997, 260, 648, 436, 716, 385, 873, 634, 682,
       483, 854, 453, 653, 154, 876, 838])

In [44]:
a1.size

20

In [45]:
a1.reshape((4, 5)) #redefine the shape of array.

array([[262, 974, 149, 959, 997],
       [260, 648, 436, 716, 385],
       [873, 634, 682, 483, 854],
       [453, 653, 154, 876, 838]])

In [46]:
G.reshape(2,5)

array([[1703, 9369, 1894, 5512, 2325],
       [5908, 6886, 5218, 1407, 4095]])

In [6]:
a1.reshape((5, 4))

ValueError: cannot reshape array of size 20 into shape (3,4)

In [7]:
a2 = a1.reshape((4, 5))

In [8]:
a2.ndim

2

In [9]:
a2.shape

(4, 5)

In [10]:
a2.size

20

In [11]:
a2

array([[216, 602, 334, 299, 661],
       [625, 597, 180, 906, 965],
       [678, 855, 307, 178, 626],
       [169, 693, 596, 839, 803]])

In [12]:
a2.reshape((2, 2, 5))

array([[[216, 602, 334, 299, 661],
        [625, 597, 180, 906, 965]],

       [[678, 855, 307, 178, 626],
        [169, 693, 596, 839, 803]]])

In [13]:
a2.reshape((20))

array([216, 602, 334, 299, 661, 625, 597, 180, 906, 965, 678, 855, 307,
       178, 626, 169, 693, 596, 839, 803])

In [ ]:
a2

In [ ]:
a2.shape

In [ ]:
a2.T

In [ ]:
a2.transpose()

In [ ]:
type(a2)

##### access the data the from ndarray

In [14]:
a1

array([216, 602, 334, 299, 661, 625, 597, 180, 906, 965, 678, 855, 307,
       178, 626, 169, 693, 596, 839, 803])

In [15]:
a1[0]

216

In [16]:
a1[-1]

803

In [17]:
a1[:3]

array([216, 602, 334])

In [18]:
a1[3:7]

array([299, 661, 625, 597])

In [19]:
a1[::2]

array([216, 334, 661, 597, 906, 678, 307, 626, 693, 839])

In [20]:
a1[1::2]

array([602, 299, 625, 180, 965, 855, 178, 169, 596, 803])

In [21]:
a2

array([[216, 602, 334, 299, 661],
       [625, 597, 180, 906, 965],
       [678, 855, 307, 178, 626],
       [169, 693, 596, 839, 803]])

In [22]:
a2[1, 4]

965

In [23]:
a2[::,::]

array([[216, 602, 334, 299, 661],
       [625, 597, 180, 906, 965],
       [678, 855, 307, 178, 626],
       [169, 693, 596, 839, 803]])

In [24]:
a2[0,::]

array([216, 602, 334, 299, 661])

In [25]:
a2[0]

array([216, 602, 334, 299, 661])

In [26]:
a2[-1]

array([169, 693, 596, 839, 803])

In [27]:
a2[:2,]

array([[216, 602, 334, 299, 661],
       [625, 597, 180, 906, 965]])

In [28]:
a2

array([[216, 602, 334, 299, 661],
       [625, 597, 180, 906, 965],
       [678, 855, 307, 178, 626],
       [169, 693, 596, 839, 803]])

In [30]:
a2[, 0]

SyntaxError: invalid syntax (Temp/ipykernel_11968/2797449576.py, line 1)

In [31]:
a2[:, 0]

array([216, 625, 678, 169])

In [32]:
a2[:, -1]

array([661, 965, 626, 803])

In [33]:
a2[:2, :3]

array([[216, 602, 334],
       [625, 597, 180]])

In [34]:
a2

array([[216, 602, 334, 299, 661],
       [625, 597, 180, 906, 965],
       [678, 855, 307, 178, 626],
       [169, 693, 596, 839, 803]])

In [35]:
a2[2, 2:4]

array([307, 178])

In [36]:
a2[:3, 2:]

array([[334, 299, 661],
       [180, 906, 965],
       [307, 178, 626]])

In [37]:
a2[1:3, :3]

array([[625, 597, 180],
       [678, 855, 307]])

In [38]:
a2[1, 2]

180

In [39]:
a1

array([216, 602, 334, 299, 661, 625, 597, 180, 906, 965, 678, 855, 307,
       178, 626, 169, 693, 596, 839, 803])

In [ ]:
a1[1]

In [40]:
a1[1:2]

array([602])

In [41]:
a2

array([[216, 602, 334, 299, 661],
       [625, 597, 180, 906, 965],
       [678, 855, 307, 178, 626],
       [169, 693, 596, 839, 803]])

In [42]:
a2[1, 2]

180

In [43]:
a2[1:2, 2:3]

array([[180]])

In [44]:
a2[1, 2:3]

array([180])

In [45]:
a2[1:2, 2]

array([180])

In [46]:
a2

array([[216, 602, 334, 299, 661],
       [625, 597, 180, 906, 965],
       [678, 855, 307, 178, 626],
       [169, 693, 596, 839, 803]])

In [47]:
a2[2, 2] = 0

In [48]:
a2

array([[216, 602, 334, 299, 661],
       [625, 597, 180, 906, 965],
       [678, 855,   0, 178, 626],
       [169, 693, 596, 839, 803]])

In [ ]:
a2[2:, 3:] = -1

In [49]:
a2

array([[216, 602, 334, 299, 661],
       [625, 597, 180, 906, 965],
       [678, 855,   0, 178, 626],
       [169, 693, 596, 839, 803]])

In [50]:
a2[0, 3:] = [-1, -2]

In [51]:
a2

array([[216, 602, 334,  -1,  -2],
       [625, 597, 180, 906, 965],
       [678, 855,   0, 178, 626],
       [169, 693, 596, 839, 803]])

In [ ]:
a2 + 10

In [ ]:
a2 / 10

In [ ]:
a2 

In [ ]:
a2 % 2 == 0

In [ ]:
a2[ a2 % 2 != 0 ]

In [53]:
# get the 20 random 2 digit numbers in 2D ndarray of shape 4, 5     #################
a3 = np.random.randint(10, 100, 20).reshape((4, 5))

In [55]:
a3

array([[26, 98, 52, 41, 39],
       [22, 45, 50, 51, 88],
       [69, 91, 38, 69, 69],
       [90, 49, 66, 70, 55]])

In [56]:
a1

array([216, 602, 334,  -1,  -2, 625, 597, 180, 906, 965, 678, 855,   0,
       178, 626, 169, 693, 596, 839, 803])

In [ ]:
# get the numbers GE 500 from a1
a1[ a1 >= 500 ]

In [ ]:
# get the negative numbers from a1
a1[a1 < 0]

In [ ]:
a3

In [57]:
# get the numbers GE 50 from a3
a3[ a3 >= 50 ]

array([98, 52, 50, 51, 88, 69, 91, 69, 69, 90, 66, 70, 55])

In [59]:
#get the no GE 100 from a3.
a3[a3 >= 10]

array([26, 98, 52, 41, 39, 22, 45, 50, 51, 88, 69, 91, 38, 69, 69, 90, 49,
       66, 70, 55])

In [65]:
#get the number between 50 and 100 from a3.   # & (and) pipe (or)
a3[ (a3 >= 50) & (a3 <= 75)]

array([52, 50, 51, 69, 69, 69, 66, 70, 55])

In [62]:
# get the numbers LE 80 from a3
a3[a3 <= 80]

array([26, 52, 41, 39, 22, 45, 50, 51, 69, 38, 69, 69, 49, 66, 70, 55])

In [63]:
# get the numbers from a3 between 50 and 80
a3[ a3 >= 50 and a3 <= 80 ]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
a3 >= 50

In [ ]:
a3 <= 80

In [ ]:
(a3 >= 50) & (a3 <= 80)

In [ ]:
a3[ (a3 >= 50) & (a3 <= 80) ]

In [ ]:
a3

In [ ]:
# get the data which is LE 20 or GE 90
a3[ (a3 <= 20) | (a3 >= 90) ]

In [ ]:
(a3 <= 20) 